cmake_minimum_required(VERSION 3.28)
project(Opticluster)
include_directories("/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/Rcpp/libs/")
include_directories("/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/Rcpp/include/")
include_directories("/Library/Frameworks/R.framework/Versions/4.3-arm64/Headers/")
link_libraries($$(LAPACK_LIBS) $$(BLAS_LIBS) $$(FLIBS) -lprofiler)
set(CMAKE_CXX_STANDARD 11)
add_executable(Opticluster main.cpp
        MothurDependencies/ClusterCommand.h
        MothurDependencies/ClusterMetric.cpp
        MothurDependencies/ClusterMetric.h
        MothurDependencies/ListVector.h
        MothurDependencies/OptiCluster.h
        MothurDependencies/OptiData.h
        MothurDependencies/OptiMatrix.h
        MothurDependencies/Utils.h
        UtilsTestFixture.cpp
        Utils.cpp
        ListVector.cpp
        OptiMatrix.cpp
        ListVectorTestFixture.cpp
        OptimatrixAdapterTestFixture.cpp
        OptiData.cpp
        OptimatrixAdapter.cpp
        OptiClusterTestFixture.cpp
        OptiCluster.cpp
        OptiDataTestFixture.cpp
        ClusterCommand.cpp
        Adapters/OptimatrixAdapter.h
        MothurDependencies/Metrics/accuracy.hpp
        MothurDependencies/Metrics/f1score.hpp
        MothurDependencies/Metrics/fdr.hpp
        MothurDependencies/Metrics/fn.hpp
        MothurDependencies/Metrics/fp.hpp
        MothurDependencies/Metrics/fpfn.hpp
        MothurDependencies/Metrics/mcc.hpp
        MothurDependencies/Metrics/npv.hpp
        MothurDependencies/Metrics/ppv.hpp
        MothurDependencies/Metrics/sensitivity.hpp
        MothurDependencies/Metrics/specificity.hpp
        MothurDependencies/Metrics/tn.hpp
        MothurDependencies/Metrics/tp.hpp
        MothurDependencies/Metrics/tptn.hpp
        Cluster.cpp
        MothurDependencies/Cluster.h
        RAbundVector.cpp
        MothurDependencies/RAbundVector.h
        MothurDependencies/DataVector.h
        SingleLinkage.cpp
        SingleLinkage.cpp
        MothurDependencies/SingleLinkage.h
        AverageLinkage.cpp
        MothurDependencies/AverageLinkage.h
        WeightedLinkage.cpp
        MothurDependencies/WeightedLinkage.h
        CompleteLinkage.cpp
        MothurDependencies/CompleteLinkage.h
        SparseDistanceMatrix.cpp
        MothurDependencies/SparseDistanceMatrix.h
        MothurDependencies/PDistCell.h
        ReadPhylipMatrix.cpp
        MothurDependencies/ReadPhylipMatrix.h
        MatrixAdapter.cpp
        Adapters/MatrixAdapter.h
        Adapters/MatrixAdapter.h
        Adapters/MatrixAdapter.h
        Adapters/MatrixAdapter.h
        ClusterTestFixture.cpp
        Tests/ClusterTestFixture.h
        Tests/ListVectorTestFixture.h
        Tests/OptiClusterTestFixture.h
        Tests/OptiDataTestFixture.h
        Tests/OptimatrixAdapterTestFixture.h
        PhylipReaderTestFixture.cpp
        Tests/PhylipReaderTestFixture.h
        SparseMatrixTestFixture.cpp
        Tests/SparseMatrixTestFixture.h
        Tests/TestFixture.h
        Tests/UtilsTestFixture.h
        MatrixAdapterTestFixture.cpp
        Tests/MatrixAdapterTestFixture.h
        RAbundVectorTestFixture.cpp
        Tests/RAbundVectorTestFixture.h
        SharedFile.cpp
        MothurDependencies/SharedFile.h
        SharedFileBuilder.cpp
        MothurDependencies/SharedFileBuilder.h
        MothurDependencies/OtuAbundancePair.h
        MothurDependencies/ClusterData.h
        ClusterData.cpp
        MothurDependencies/ClusterExport.h
        OpticlusterData.cpp
        MothurDependencies/OpticlusterData.h
        CountTableAdapter.cpp
        DataFrameAdapter.cpp
        Adapters/DataFrameAdapter.h
        ClusterExportTestFixture.cpp
        Tests/ClusterExportTestFixture.h
        ClusterDataTestFixture.cpp
        Tests/ClusterDataTestFixture.h
        OptiClusterDataTestFixture.cpp
        Tests/OptiClusterDataTestFixture.h
        SharedFileTestFixture.cpp
        Tests/SharedFileTestFixture.h
        SharedFileBuilderTestFixture.cpp
        Tests/SharedFileBuilderTestFixture.h
        CountTableAdapterTestFixture.cpp
        Tests/CountTableAdapterTestFixture.h
        Tests/CountTableAdapterTestFixture.h
        DataFrameAdapterTestFixture.cpp
        Tests/DataFrameAdapterTestFixture.h
        MothurDependencies/ColumnDistanceMatrixReader.h
        ColumnDistanceMatrixReader.cpp
        Tests/ColumnReaderTestFixture.h
        ColumnReaderTestFixture.cpp
        DistanceFileReader.cpp
        Adapters/CountTableAdapter.h
        main.cpp
        DataStructures/IndexAbundancePair.h
        DataStructures/CountTable.h
)

