# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

WritePhylipFile <- function(xPosition, yPosition, data, cutoff, countTable, saveLocation) {
    invisible(.Call('_clustur_WritePhylipFile', PACKAGE = 'clustur', xPosition, yPosition, data, cutoff, countTable, saveLocation))
}

WriteColumnFile <- function(xPosition, yPosition, data, cutoff, countTable, saveLocation) {
    invisible(.Call('_clustur_WriteColumnFile', PACKAGE = 'clustur', xPosition, yPosition, data, cutoff, countTable, saveLocation))
}

DetermineIfPhylipOrColumnFile <- function(filePath) {
    .Call('_clustur_DetermineIfPhylipOrColumnFile', PACKAGE = 'clustur', filePath)
}

ProcessDistanceFiles <- function(filePath, countTable, cutoff, isSim) {
    .Call('_clustur_ProcessDistanceFiles', PACKAGE = 'clustur', filePath, countTable, cutoff, isSim)
}

ProcessSparseMatrix <- function(xPosition, yPosition, data, countTable, cutoff, isSim) {
    .Call('_clustur_ProcessSparseMatrix', PACKAGE = 'clustur', xPosition, yPosition, data, countTable, cutoff, isSim)
}

GetDistanceDataFrame <- function(fileReader) {
    .Call('_clustur_GetDistanceDataFrame', PACKAGE = 'clustur', fileReader)
}

GetCountTable <- function(fileReader) {
    .Call('_clustur_GetCountTable', PACKAGE = 'clustur', fileReader)
}

Cluster <- function(DistanceData, method, featureColumnName, binColumnName, cutoff) {
    .Call('_clustur_Cluster', PACKAGE = 'clustur', DistanceData, method, featureColumnName, binColumnName, cutoff)
}

OptiCluster <- function(DistanceData, featureColumnName, binColumnName, cutoff) {
    .Call('_clustur_OptiCluster', PACKAGE = 'clustur', DistanceData, featureColumnName, binColumnName, cutoff)
}

CreateDataFrameFromSparse <- function(countTable) {
    .Call('_clustur_CreateDataFrameFromSparse', PACKAGE = 'clustur', countTable)
}

start_profiler <- function(str) {
    .Call('_clustur_start_profiler', PACKAGE = 'clustur', str)
}

stop_profiler <- function() {
    .Call('_clustur_stop_profiler', PACKAGE = 'clustur')
}

