# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

WritePhylipFile <- function(xPosition, yPosition, data, cutoff, countTable, saveLocation) {
    invisible(.Call(`_Opticluster_WritePhylipFile`, xPosition, yPosition, data, cutoff, countTable, saveLocation))
}

MatrixToOpiMatrixCluster <- function(xPosition, yPosition, data, cutoff, countTable, maxIterations = 100L, shuffle = TRUE, isSim = FALSE) {
    .Call(`_Opticluster_MatrixToOpiMatrixCluster`, xPosition, yPosition, data, cutoff, countTable, maxIterations, shuffle, isSim)
}

ClassicCluster <- function(xPosition, yPosition, data, cutoff, method, countTable, isSimularity) {
    .Call(`_Opticluster_ClassicCluster`, xPosition, yPosition, data, cutoff, method, countTable, isSimularity)
}

start_profiler <- function(str) {
    .Call(`_Opticluster_start_profiler`, str)
}

stop_profiler <- function() {
    .Call(`_Opticluster_stop_profiler`)
}

